// ─────────────────────────────────────────────────────────────────────────────
// IMTRADE KERSEL 850 WG INSECTICIDE — Label Data
// Insecticide | Wettable Granule
// Source: Imtrade_Kersel_850_WG_Insecticide.pdf
// APVMA Approval No: 89958/136390
// Imtrade CropScience
// ─────────────────────────────────────────────────────────────────────────────
productDatabase['imtradekersel850wg'] = {
  name:             "Imtrade Kersel 850 WG Insecticide",
  company: "Imtrade",

  category:         "Insecticides",
  activeIngredient: "850 g/kg Spirotetramat",
  group:            "Group 23 Insecticide",
  modeOfAction:     "Lipid biosynthesis inhibitor - systemic and translaminar activity",
  formulation:      "Wettable Granule (WG)",
  color:            "#1e40af",
  apvma:            "89958",
  labelPdf:         "Source labels/Imtrade_Imtrade_Kersel_850_Wg_Insecticide_Label.pdf",
  sdsPdf:           "SDS Labels/IMTRADE_KERSEL_850_WG_INSECTICIDE.pdf",
  signalHeading:    "Poison",
  classification: {
    type: "Insecticide",
    target: ["Aphids", "Whitefly", "Mealybug", "Scale insects", "Thrips"],
    timing: ["Early morning and late evening"]
  },

  crops: [
    {
      crop: "Beans, Peas (Green) including Snow Peas and Sugar Snap Peas",
      cropList: ["Beans","Peas","Snow Peas","Sugar Snap Peas","Beans And Peas"],
      weeds: [
        { weed: "Green Peach Aphid (Myzus persicae)", pestList: ["Green Peach Aphid"], states: ["All"], rate: "60", rateMax: "60", unit: "g/ha", stage: "Early infestation", note: "Monitor crops and commence applications once local thresholds are reached. Where applicable, use the higher rate when periods of high pest pressure or rapid crop growth are evident or when longer residual control is desired or when crops are advanced. Continue to monitor crops and make a subsequent application as necessary. DO NOT re-apply within 7 days of a previous KERSEL 850 WG spray. DO NOT apply more than a total of 2 applications per crop. Ensure thorough coverage of the target crop - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. Note: This use is subject to a CropLife resistance management strategy. Refer to www.croplife.org.au for more information." },
        { weed: "Silverleaf Whitefly (Bemisia tabaci Biotype B)", pestList: ["Silverleaf Whitefly"], states: ["All"], rate: "85", rateMax: "115", unit: "g/ha", stage: "Early infestation", note: "Monitor crops and commence applications once local thresholds are reached. Where applicable, use the higher rate when periods of high pest pressure or rapid crop growth are evident or when longer residual control is desired or when crops are advanced. Continue to monitor crops and make a subsequent application as necessary. DO NOT re-apply within 7 days of a previous KERSEL 850 WG spray. DO NOT apply more than a total of 2 applications per crop. Ensure thorough coverage of the target crop - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. Note: This use is subject to a CropLife resistance management strategy. Refer to www.croplife.org.au for more information. Resistant populations of Silverleaf Whitefly are known to occur in some regions. KERSEL 850 WG should not be used where these populations are known to occur, or resistance is suspected. WHP: H, G 7 days. For Snow Peas and Sugar Snap Peas only H, G 3 days." },
        { weed: "Western Flower Thrips (Frankliniella occidentalis), Tomato Thrips (Frankliniella schultzei)", pestList: ["Western Flower Thrips","Tomato Thrips"], states: ["All"], rate: "85", rateMax: "115", unit: "g/ha", stage: "Flower budding", note: "Commence applications at the flower budding growth stage. Use the higher rate when periods of high pest pressure or rapid crop growth are evident or when longer residual control is desired. Continue to monitor crops and make a subsequent application as necessary. DO NOT re-apply within 7 days of a previous KERSEL 850 WG spray. DO NOT apply more than a total of 2 applications per crop. KERSEL 850 WG is not highly effective against the adult stage of thrips, however a decline in the total thrips population will occur over time as the juvenile stages are controlled. Ensure thorough coverage of the target crop - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H, G 7 days." }
      ]
    },
    {
      crop: "Brussels Sprouts",
      cropList: ["Brussels Sprouts"],
      weeds: [
        { weed: "Green Peach Aphid (Myzus persicae)", pestList: ["Green Peach Aphid"], states: ["All"], rate: "60", rateMax: "60", unit: "g/ha", stage: "Early infestation", note: "Monitor crops and commence applications once local thresholds are reached. Where applicable, use the higher rate when periods of high pest pressure or rapid crop growth are evident or when longer residual control is desired or when crops are dense or large (e.g. from the commencement of head formation). Continue to monitor crops and make subsequent applications as necessary. DO NOT re-apply within 7 days of a previous KERSEL 850 WG spray. DO NOT apply more than 3 applications per crop. Ensure thorough spray coverage of the target crop. For dilute spraying apply to the point of run-off, using application volumes of up to 1000L/ha - refer 'Application' section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. Note: The Green Peach Aphid and Silverleaf Whitefly uses are subject to CropLife resistance management strategies. Refer to www.croplife.org.au for more information. WHP: H 3 days." },
        { weed: "Silverleaf Whitefly (Bemisia tabaci Biotype B)", pestList: ["Silverleaf Whitefly"], states: ["All"], rate: "115", rateMax: "115", unit: "g/ha", stage: "Early infestation", note: "Monitor crops and commence applications once local thresholds are reached. Where applicable, use the higher rate when periods of high pest pressure or rapid crop growth are evident or when longer residual control is desired or when crops are dense or large (e.g. from the commencement of head formation). Continue to monitor crops and make subsequent applications as necessary. DO NOT re-apply within 7 days of a previous KERSEL 850 WG spray. DO NOT apply more than 3 applications per crop. Ensure thorough spray coverage of the target crop. For dilute spraying apply to the point of run-off, using application volumes of up to 1000L/ha - refer 'Application' section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. Note: The Green Peach Aphid and Silverleaf Whitefly uses are subject to CropLife resistance management strategies. Refer to www.croplife.org.au for more information. WHP: H 3 days." }
      ]
    },
    {
      crop: "Peppers (Capsicum and Chilli), Tomatoes (Field and protected cropping systems)",
      cropList: ["Peppers","Capsicum","Chilli","Tomatoes","Peppers And Tomatoes"],
      weeds: [
        { weed: "Green Peach Aphid (Myzus persicae)", pestList: ["Green Peach Aphid"], states: ["All"], rate: "60", rateMax: "60", unit: "g/ha", stage: "Early infestation", note: "Monitor crops and commence applications once local thresholds are reached. Where applicable, use the higher rate when periods of high pest pressure or rapid crop growth are evident or when longer residual control is desired or when crops are dense or large. Continue to monitor crops and make subsequent applications as necessary. DO NOT re-apply within 7 days of a previous KERSEL 850 WG spray. DO NOT apply more than 3 applications per crop. KERSEL 850 WG is not highly effective against the adult stage of Western Flower Thrips, however a decline in the total thrips population will occur over time as the juvenile stages are controlled. Dilute or concentrate spraying is recommended for trellised crops (e.g. glasshouse crops). Ensure thorough spray coverage of the target crop. For Dilute spraying apply to the point of run-off, using application volumes of up to 1000L/ha - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. Note: Green Peach Aphid and Silverleaf Whitefly use is subject to a CropLife resistance management strategy. Refer to www.croplife.org.au for more information. Resistant populations of Silverleaf Whitefly are known to occur in some regions. KERSEL 850 WG should not be used where these populations are known to occur, or resistance is suspected. WHP: H 1 day." },
        { weed: "Silverleaf Whitefly (Bemisia tabaci Biotype B), Western Flower Thrips (Frankliniella occidentalis)", pestList: ["Silverleaf Whitefly","Western Flower Thrips"], states: ["All"], rate: "85", rateMax: "115", unit: "g/ha", stage: "Early infestation", note: "Monitor crops and commence applications once local thresholds are reached. Where applicable, use the higher rate when periods of high pest pressure or rapid crop growth are evident or when longer residual control is desired or when crops are dense or large. Continue to monitor crops and make subsequent applications as necessary. DO NOT re-apply within 7 days of a previous KERSEL 850 WG spray. DO NOT apply more than 3 applications per crop. KERSEL 850 WG is not highly effective against the adult stage of Western Flower Thrips, however a decline in the total thrips population will occur over time as the juvenile stages are controlled. Dilute or concentrate spraying is recommended for trellised crops (e.g. glasshouse crops). Ensure thorough spray coverage of the target crop. For Dilute spraying apply to the point of run-off, using application volumes of up to 1000L/ha - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. Note: Green Peach Aphid and Silverleaf Whitefly use is subject to a CropLife resistance management strategy. Refer to www.croplife.org.au for more information. Resistant populations of Silverleaf Whitefly are known to occur in some regions. KERSEL 850 WG should not be used where these populations are known to occur, or resistance is suspected. WHP: H 1 day." }
      ]
    },
    {
      crop: "Onions, Bulb",
      cropList: ["Onions","Bulb Onions"],
      weeds: [
        { weed: "Onion Thrips (Thrips tabaci)", pestList: ["Onion Thrips"], states: ["All"], rate: "60", rateMax: "60", unit: "g/ha", stage: "Early infestation", note: "Monitor crops and commence applications once local thresholds are reached. Continue to monitor crops and make a subsequent application as necessary. DO NOT re-apply within 14 days of a previous KERSEL 850 WG spray. DO NOT apply more than 2 applications per crop. KERSEL 850 WG is not highly effective against the adult stage of thrips, however a decline in the total thrips population will occur over time as the juvenile stages are controlled. Ensure thorough coverage of the target crop - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 7 days." }
      ]
    },
    {
      crop: "Citrus",
      cropList: ["Citrus"],
      weeds: [
        { weed: "Red Scale, Mussel Scale, White Louse Scale (Citrus Snow Scale), Soft Brown Scale, Pink Wax Scale, Citrus Mealybug (suppression only)", pestList: ["Red Scale","Mussel Scale","White Louse Scale","Soft Brown Scale","Pink Wax Scale","Citrus Mealybug"], states: ["All"], rate: "6", rateMax: "10", unit: "g/100L", stage: "Post-flowering", note: "Monitor crops and commence applications after flowering at the onset of crawler emergence or when pest numbers reach economic threshold. Continue to monitor crops and apply a second application 21-35 days after the first application if required. Applications to an established pest population where mature adults are present and dominate the population will be ineffective. Where applicable use the higher rate under high pest pressure or to provide longer residual control. For Red Scale, the higher rate will provide control where crawlers have settled and whitecaps are visible. DO NOT exceed 1.1kg of KERSEL 850 WG per hectare. A total of 3 applications can be made in Citrus in a 12 month period, however no more than 2 applications should be made within 90 days of harvest. Apply thoroughly to ensure complete coverage, using dilute spraying equipment in up to 10,000L/ha water (concentrate spraying is not appropriate for this use) - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specific spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 3 weeks." },
        { weed: "Kelly's Citrus Thrips", pestList: ["Kelly's Citrus Thrips"], states: ["All"], rate: "6", rateMax: "10", unit: "g/100L", stage: "Post-flowering", note: "Monitor crops from flowering onwards for the presence of Kelly's Citrus Thrips. Apply KERSEL 850 WG after flowering, once local pest thresholds are reached. A single application may be suitable where thrips pressure is low. Continue to monitor crops and where thrips pressure is moderate to high apply a second application, no less than 14 days after the first, and prior to calyx closure. Use the higher rate under high pest pressure or to provide longer residual control. DO NOT exceed 4.0L of KERSEL 850 WG per hectare. Overlapping cropping situations e.g. Lemons, Valencia Oranges: if any maturing fruit is present on the tree and is within 6 weeks of harvest, a second application for control of Kelly's Citrus Thrips should be at least 21 days after the first and ideally prior to calyx closure. A total of 3 applications can be made in Citrus in a 12 month period, however no more than 2 applications should be made within 90 days of harvest. Apply thoroughly to ensure complete coverage, using dilute spraying equipment in up to 10,000L/ha water (concentrate spraying is not appropriate for this use) - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 3 weeks." }
      ]
    },
    {
      crop: "Grapes",
      cropList: ["Grapes"],
      weeds: [
        { weed: "Grapevine Scale (Parthenolecanium persicae) (suppression only)", pestList: ["Grapevine Scale"], states: ["All"], rate: "10", rateMax: "10", unit: "g/100L", stage: "Post-bud burst", note: "Monitor crops following bud burst. Commence applications at the onset of crawler emergence or when pest numbers reach an economic threshold. To ensure there is sufficient foliage for product uptake DO NOT apply prior to 6-leaf stage (EL 13). Continue to monitor crops and apply a second application 21 to 28 days after the first application. For all pests, applications to an established pest population where mature adults are present and dominate the population, will be ineffective. DO NOT apply more than 2 applications per crop with a minimum of 14 days between applications. Apply thoroughly to ensure complete coverage. Apply by dilute or concentrate spraying equipment. Apply the same total amount of KERSEL 850 WG to the target crop whether applying KERSEL 850 WG by dilute or concentrate spraying methods. For concentrate spraying, DO NOT use at rates greater than two times the dilute spraying rate (i.e. at a concentration factor greater than 2X) - refer 'Application' section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 4 weeks. Note: If Grapes are likely to be exported as wine, fresh or dried fruit also refer to advice under Export of Treated produce heading." }
      ]
    },
    {
      crop: "Pome Fruit",
      cropList: ["Pome Fruit","Apples","Pears"],
      weeds: [
        { weed: "Longtailed Mealybug (Pseudococcus longispinus), Tuber Mealybug (Pseudococcus viburni), Woolly Apple Aphid (Eriosoma lanigerum) (suppression only)", pestList: ["Longtailed Mealybug","Tuber Mealybug","Woolly Apple Aphid"], states: ["All"], rate: "10", rateMax: "10", unit: "g/100L", stage: "Post-flowering", note: "Monitor crops following flowering. Commence applications at the onset of crawler emergence or when pest numbers reach an economic threshold. To ensure there is sufficient foliage for product uptake: For Apples: DO NOT apply prior to petal fall. For Pears: DO NOT apply prior to fruitlets reaching 10mm in diameter. Mealybug and Woolly Apple Aphid: Continue to monitor crops and apply a second application 14 to 28 days after the first application. For all pests, applications to an established pest population where mature adults are present and dominate the population will be ineffective. DO NOT apply more than 3 applications per crop with a minimum 14 days between applications. Apply thoroughly to ensure complete coverage. Apply by dilute or concentrate spraying equipment. Apply the same total amount of product to the target crop whether applying this product by dilute or concentrate spraying methods. For concentrate spraying, DO NOT use at rates greater than two times the dilute spraying rate (i.e. at a concentration factor greater than 2X) - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 3 weeks." },
        { weed: "San Jose Scale (Quadraspidiotus perniciosus)", pestList: ["San Jose Scale"], states: ["All"], rate: "8", rateMax: "8", unit: "g/100L", stage: "Post-flowering", note: "Monitor crops following flowering. Commence applications at the onset of crawler emergence or when pest numbers reach an economic threshold. Continue monitoring and apply further applications when new generations emerge. DO NOT re-apply within 14 days of a previous KERSEL 850 WG application. For all pests, applications to an established pest population where mature adults are present and dominate the population will be ineffective. DO NOT apply more than 3 applications per crop with a minimum 14 days between applications. Apply thoroughly to ensure complete coverage. Apply by dilute or concentrate spraying equipment. Apply the same total amount of product to the target crop whether applying this product by dilute or concentrate spraying methods. For concentrate spraying, DO NOT use at rates greater than two times the dilute spraying rate (i.e. at a concentration factor greater than 2X) - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 3 weeks." }
      ]
    },
    {
      crop: "Stone Fruit",
      cropList: ["Stone Fruit","Cherries","Nectarines","Peaches","Plums","Apricots"],
      weeds: [
        { weed: "Tuber Mealybug (Pseudococcus viburni), Longtailed Mealybug (Pseudococcus longispinus)", pestList: ["Tuber Mealybug","Longtailed Mealybug"], states: ["All"], rate: "10", rateMax: "10", unit: "g/100L", stage: "Post-petal fall", note: "Monitor crops following petal fall. Commence applications at the onset of crawler emergence or when pest numbers reach an economic threshold. To ensure there is sufficient foliage for product uptake DO NOT apply prior to shuck fall. Mealybug: Continue to monitor crops and apply a second application 14 to 28 days after the first application. For all pests, applications to an established pest population where mature adults are present and dominate the population will be ineffective. Cherries: DO NOT apply more than 2 applications per crop of cherries with a minimum 14 days between applications. Stone Fruit other than Cherries: DO NOT apply more than 3 applications per crop, with no more than 2 applications made later than 21 days after shuck fall and with a minimum 14 days between applications. Apply thoroughly to ensure complete coverage. Apply by dilute or concentrate spraying equipment. Apply the same total amount of product to the target crop whether applying this product by dilute or concentrate spraying methods. For concentrate spraying, DO NOT use at rates greater than two times the dilute spraying rate (i.e. at a concentration factor greater than 2X) - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 3 weeks." },
        { weed: "Black Cherry Aphid (Myzus cerasi), Black Peach Aphid (Brachycaudus persicae)", pestList: ["Black Cherry Aphid","Black Peach Aphid"], states: ["All"], rate: "8", rateMax: "8", unit: "g/100L", stage: "Post-petal fall", note: "Monitor crops following petal fall. Commence applications at the onset of crawler emergence or when pest numbers reach an economic threshold. Aphids: Continue to monitor crops and apply a second application 14 to 21 days after the first application if required. For all pests, applications to an established pest population where mature adults are present and dominate the population will be ineffective. Cherries: DO NOT apply more than 2 applications per crop of cherries with a minimum 14 days between applications. Stone Fruit other than Cherries: DO NOT apply more than 3 applications per crop, with no more than 2 applications made later than 21 days after shuck fall and with a minimum 14 days between applications. Apply thoroughly to ensure complete coverage. Apply by dilute or concentrate spraying equipment. Apply the same total amount of product to the target crop whether applying this product by dilute or concentrate spraying methods. For concentrate spraying, DO NOT use at rates greater than two times the dilute spraying rate (i.e. at a concentration factor greater than 2X) - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 3 weeks." },
        { weed: "San Jose Scale (Quadraspidiotus perniciosus)", pestList: ["San Jose Scale"], states: ["All"], rate: "8", rateMax: "8", unit: "g/100L", stage: "Post-petal fall", note: "Monitor crops following petal fall. San Jose Scale: Continue monitoring and apply further applications when new generations emerge. DO NOT re-apply within 14 days of a previous KERSEL 850 WG application. For all pests, applications to an established pest population where mature adults are present and dominate the population will be ineffective. Cherries: DO NOT apply more than 2 applications per crop of cherries with a minimum 14 days between applications. Stone Fruit other than Cherries: DO NOT apply more than 3 applications per crop, with no more than 2 applications made later than 21 days after shuck fall and with a minimum 14 days between applications. Apply thoroughly to ensure complete coverage. Apply by dilute or concentrate spraying equipment. Apply the same total amount of product to the target crop whether applying this product by dilute or concentrate spraying methods. For concentrate spraying, DO NOT use at rates greater than two times the dilute spraying rate (i.e. at a concentration factor greater than 2X) - refer \"Application\" section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. WHP: H 3 weeks." }
      ]
    },
    {
      crop: "Cotton",
      cropList: ["Cotton"],
      weeds: [
        { weed: "Silverleaf Whitefly (Bemisia tabaci)", pestList: ["Silverleaf Whitefly"], states: ["All"], rate: "115", rateMax: "115", unit: "g/ha", stage: "Early population", note: "Monitor crops and commence applications once local thresholds are reached. Use the higher rate when periods of high pest pressure or rapid crop growth are evident, when longer residual control is desired or when crops are well advanced. Continue to monitor crops and make a subsequent application as necessary. DO NOT re-apply within 14 days of a previous KERSEL 850 WG spray. DO NOT apply more than 2 applications per crop. KERSEL 850 WG may not control Silverleaf Whitefly adults and eggs, however a decline in the total Silverleaf Whitefly population will occur over time as the juvenile stages are controlled. Ensure thorough coverage of the target crop - refer 'Application' section in GENERAL INSTRUCTIONS. Always add a specified spray adjuvant - refer 'Adjuvant' section in GENERAL INSTRUCTIONS. Note: These uses are subject to CropLife resistance management strategies. Refer to www.croplife.org.au for more information. WHP: H 3 weeks." }
      ]
    }
  ],

  restraints: [
    "DO NOT allow bystanders to come into contact with the spray cloud",
    "DO NOT apply under hazardous temperature inversion conditions",
    "DO NOT apply unless wind speed is 3-20 km/hr",
    "DO NOT re-enter treated areas until spray has dried"
  ],

  compatibility: {
    compatible:   ["Imtrade Pronto Spray Adjuvant"],
    incompatible: ["Amistar", "Du-Wett"],
    notes:        ["May have adverse effects on predatory mites where IPM practiced"]
  },

  withholding: {
    harvest: "Peppers (Capsicum and Chilli), Tomatoes: 1 day; Snow Peas, Sugar Snap Peas, Brussels Sprouts: 3 days; Beans, Onions (Bulb), Peas (except Snow Peas and Sugar Snap Peas): 7 days; Citrus, Cotton, Pome Fruit, Stone Fruit: 3 weeks; Grapes: 4 weeks",
    grazing: "Brussels Sprouts: DO NOT graze treated crops. Snow Peas and Sugar Snap Peas: 3 days. Beans, Peas (except Snow Peas and Sugar Snap Peas): 7 days. Cotton: DO NOT feed cotton fodder, stubble or trash to livestock. Export Slaughter Interval (ESI): 3 days."
  },

  surfactant:     "Imtrade Pronto Spray Adjuvant - Vegetables (except Onions, Bulb): 0.5 to 1.0L/ha or 200mL/100L. Citrus, Grapes, Pome Fruit, Stone Fruit: 50 mL/100L. Onions, Bulbs: 0.5 to 1.0L/100L. Cotton: 1.0L/ha.",
  sprayerCleanup: "Triple-rinse containers. Do not dispose of undiluted chemicals on-site."
};
