productDatabase['weedmaster_duo'] = {
    "name": "Nufarm weedmaster® DUO Herbicide",
    "company": "Nufarm",

    "category": "Herbicides",
    "activeIngredient": "Glyphosate (600 g/L)",
    "group": "Group 9 (Glycine Derivative)",
    "modeOfAction": "Non-selective systemic herbicide; inhibits EPSP synthase",
    "formulation": "Soluble Liquid (SL)",
    "color": "#6366f1",
    "apvma": "53576",
    "labelPdf": "Source labels/Nufarm_WeedmasterDUO_Label.pdf",
    "sdsPdf": "SDS Labels/WEEDMASTER_DUO.pdf",
    "signalHeading": "Caution",
    "classification": {
        "type": "Herbicide",
        "target": [
            "Broadleaf Weeds",
            "Grasses",
            "Perennial Weeds"
        ],
        "timing": [
            "Post-emergent"
        ]
    },
    "crops": [
      {
        crop: "Pastures and Forests. Planting interval: wait a minimum of 1 day per gram Associate before planting. Commercial and Industrial areas, Rights of way, Domestic and public service areas DO NOT USE ON ALKALINE SOILS",
        cropList: ["Pastures", "Forests. Planting interval: wait a minimum of 1 day per gram Associate before planting. Commercial", "Industrial areas", "Rights of way", "Domestic", "public service areas DO NOT USE ON ALKALINE SOILS"],
        weeds: [
          { weed: "Blackberry (Rubus spp.) Volunteer pine wildings (suppression only)", pestList: ["Blackberry Volunteer Pine Wildings (Suppression Only)"], states: ["All"], rate: "400", unit: "mL/100L", rateText: "400 mL per 100 L water", notes: "For Blackberries, apply from flowering until prior to leaf yellowing. Due to widespread picking of Blackberries by the public, it is not recommended that the product be applied to bushes bearing mature fruit. Use Pulse Penetrant at the rate of 500 mL per 100 L water. Application to Pine wildings less than 50 cm in height should be controlled when actively growing." },
          { weed: "Coppice control (Eucalyptus globulus)", pestList: ["Coppice Control"], states: ["All"], rate: "8", unit: "L/ha", rateText: "8 L per ha", notes: "Use Pulse Penetrant at the rate of 500 mL per 100 L water. For coppice control, apply using a minimum 400 L/ha using a double pass application method to coppice up to a maximum 1.5 m in height. Target every stem separately. DO NOT disturb for 6 weeks to allow maximum translocation." },
          { weed: "Bracken (Pteridium esculentum)", pestList: ["Bracken"], states: ["All"], rate: "4", unit: "L/ha", rateText: "4 L per ha", notes: "For Bracken, apply when fronds are fully unfurled but prior to first frosts. For boom application, refer to Boom application section. Use Pulse Penetrant at the rate of 500 mL per 100 L of water. DO NOT disturb Bracken for minimum 6 weeks after application." },
          { weed: "Fog grass (Holcuslanatus) Gorse (Ulex europaeus), Lantana (Lantana camara), St John's wort (Hypericum perforarum), Sorrel (Rumex acetosella) Sweet briar (Rosa rubiginosa) Topped lavender (Lavandula stoechas)", pestList: ["Fog Grass (Holcuslanatus) Gorse", "Lantana", "St John\u2019S Wort", "Sorrel Sweet Briar Topped Lavender"], states: ["All"], rate: "4", unit: "L/ha", rateText: "4 L per ha", notes: "Use Pulse® Penetrant at the rate of 500 mL per 100 L of water. For Gorse, apply when actively growing at any time of year, except Spring. For Lantana, apply when actively growing. DO NOT apply during periods of Summer drought stress. For St John's wort, apply when actively growing from Spring to Summer. For Sweet briar, apply when in full leaf, prior to leaf fall. For Topped lavender, Fog grass and Sorrel, apply when actively growing. For Sorrel apply 10-30 g when actively growing. DO NOT app..." }
        ]
      },
      {
        crop: "Weed Table — All Situations",
        cropList: ["Weed Table \u2014 All Situations"],
        weeds: [
          { weed: "Alligator weed^", pestList: ["Alligator Weed^"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply when actively growing, from Summer through Winter. Floating form only." },
          { weed: "Bamboo (Bambusa spp.)", pestList: ["Bamboo"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply to actively growing foliage and/or regrowth which is between 1m and 2m tall. Cut stump: Dilute 1:6 ie. mix 1 part of this product plus 6 parts water. Cut stems back to 20cm high, pour mixture down hollow stem or wet the cut." },
          { weed: "Bent grass (Agrostis capillaris)", pestList: ["Bent Grass"], states: ["All"], rate: "2.5", unit: "L/ha", rateText: "2.5 L/ha", notes: "Apply to actively growing plants in late Spring when they have some seed head development but before Summer moisture stress. Bent grass should NOT be heavily grazed at spraying. Follow up management is required to limit seedling re-establishment. Full disturbance with a tyned implement should follow, 10-21 days after spraying. Application of this product should be followed by a Summer crop and/or by re-seeding pasture or crop the following Autumn." },
          { weed: "Blady grass (Imperata cylindrica)", pestList: ["Blady Grass"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants at the early head stage." },
          { weed: "Bracken (Pteridium esculentum)", pestList: ["Bracken"], states: ["All"], rate: "9", unit: "L/ha", notes: "For boom application, always add Pulse® Penetrant, otherwise reduced results will occur. Addition of Pulse® Penetrant (500 mL/100L spray) may improve control with handgun application. Wiper application is recommended, see WIPER EQUIPMENT. Double pass application is required for ropewick equipment. Bracken should be slashed in Winter/Spring prior to treatment. Apply this product when fronds are fully unfurled actively growing fronds but prior to frosts. Visible symptoms may not be fully appare..." },
          { weed: "Brown beetle grass^ (Diplachne spp.)", pestList: ["Brown Beetle Grass^"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply to actively growing plants. DO NOT apply to partially submerged plants." },
          { weed: "Carpet grass (Axonopus spp.)", pestList: ["Carpet Grass"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply to actively growing plants at the early head stage." },
          { weed: "Cocksfoot (Dactylis glomerata)", pestList: ["Cocksfoot"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply to actively growing plants at the early head stage." },
          { weed: "Couch (Cynodon dactylon)", pestList: ["Couch"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants when most have reached the early head stage. In SA and WA apply to active plants during Oct-Nov for best results. Addition of Pulse® Penetrant (500 mL/100L spray) may improve control. No disturbance for 5 weeks minimum after application." },
          { weed: "Cumbungi^ (Typha spp.)", pestList: ["Cumbungi^"], states: ["All"], rate: "9", unit: "L/ha", rateText: "9 L/ha", notes: "Apply to actively growing plants at the early head to full head stage (Summer-Autumn). Re-treatment may be required to restrict seedling re-establishment. Application by wiper equipment is recommended (not Tasmania). Refer WIPER EQUIPMENT section." },
          { weed: "Flatweed (Cat's ear) (Hypochoeris radicata)", pestList: ["Flatweed (Cat\u2019S Ear)"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply to fully developed rosettes at the early flower stage." },
          { weed: "Glyceria (Glyceria maxima)", pestList: ["Glyceria"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply to actively growing plants at the mature head stage in late Summer-Autumn. Add Nufarm LI 700® at 250-500 mL/100L. NOTE: Control of Glyceria is only allowable in dry drains and channels and dry margins of dams, lakes and streams. DO NOT apply to weeds growing in or over water. DO NOT spray across open bodies of water, and DO NOT allow spray to enter water. DO NOT allow water to return to dry channels within 4 days of application." },
          { weed: "Guinea grass (Panicum maximum)", pestList: ["Guinea Grass"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants when most have reached the early head stage. For WIPER application refer WIPER EQUIPMENT section." },
          { weed: "Hoary cress (Cardaria draba)", pestList: ["Hoary Cress"], states: ["All"], rate: "1.5", unit: "L/ha", rateText: "1.5 L/ha", notes: "For maximum long term reduction, apply from late July to September when plants are in late rosette to flowering stage. Plants should be actively growing and not under stress of drought, frost or waterlogging. Application may be integrated with long fallows. Cultivation may start 7 days after spraying. Wiper equipment may be used where sufficient stem elongation occurs, refer to WIPER EQUIPMENT section. In Tasmania add Nufarm LI 700 at 250-500 mL/100L spray." },
          { weed: "Johnson grass (Sorghum halepense) Kangaroo grass (Themeda australis) Kikuyu grass (Pennisetum clandestinum)", pestList: ["Johnson Grass Kangaroo Grass Kikuyu Grass"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply to actively growing plants at the early head stage. For application by wiper equipment on Johnson grass, off-type and Volunteer sorghum refer to WIPER EQUIPMENT section." },
          { weed: "Lovegrass, African (Eragrostis curvula)", pestList: ["Lovegrass", "African"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply to actively growing plants. Re-treatment and/or pasture improvement is recommended to restrict seedling re-establishment." },
          { weed: "Ludwigia peruviana", pestList: ["Ludwigia Peruviana"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply when actively growing and at or beyond the early bloom stage of growth, but before Autumn colour changes occur. Thorough coverage is necessary for best control." },
          { weed: "Nutgrass (Cyperus rotundus) Does not refer to other Cyperus spp. which may be locally known as nutgrass.", pestList: ["Nutgrass Does Not Refer To Other Cyperus Spp. Which May Be Locally Known As Nutgrass."], states: ["All"], rate: "6", unit: "L/ha", notes: "NON-CULTIVATED SITUATIONS: Apply to actively growing plants in late Summer-Autumn (Feb-Apr) when at least 20% have reached the head stage. ARABLE LAND: Make FIRST APPLICATION to actively growing plants when at least 20% have reached the head stage (normally about Feb). After allowing maximum re-emergence to occur (normally in 6-8 weeks) it is essential to make a SECOND APPLICATION. NOTE: In arable land Nutgrass may rapidly regenerate from isolated nuts. Follow up treatments should be made as ..." },
          { weed: "Pampas grass (Cortaderia spp.)", pestList: ["Pampas Grass"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply to actively growing plants during Spring, Summer or Autumn. Ensure complete coverage of the foliage. For best results, apply after flowering. For easier access, large plants may be cut or burnt prior to spraying, but first allow regrowth to reach 1m. Use the higher rate on plants over 1 m high. LOW VOLUME APPLICATION: Use 1:9 mixture of this product to water. Apply 2x2mL per 0.5 m height. Ensure spray contacts all foliage." },
          { weed: "Paragrass^ (Brachiara mutica)", pestList: ["Paragrass^"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants when most have reached the early head stage." },
          { weed: "Paspalum (Paspalum dilitatum)", pestList: ["Paspalum"], states: ["All"], rate: "6", unit: "L/ha" },
          { weed: "Pellitory (Parietaria judaica)", pestList: ["Pellitory"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply to actively growing plants prior to seeding. Repeat applications may be necessary to control seedlings and/or regrowth." },
          { weed: "Phalaris (Phalaris aquatica)", pestList: ["Phalaris"], states: ["All"], rate: "3", rateMax: "6", unit: "L/ha", notes: "Apply to actively growing plants during Winter-Spring. Use the lower rate where only knockdown is required eg. prior to burning of firebreaks. Burning can usually start 14-21 days after spraying. For long term control increase to the higher rate." },
          { weed: "Phragmites, Common reed^ (Phragmites australis)", pestList: ["Phragmites", "Common Reed^"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing, fully developed plants approaching the early head stage. Visible symptoms of control may be slow to develop and may not be fully apparent until the next season. For application by wiper equipment refer to WIPER EQUIPMENT section." },
          { weed: "Plantains (Plantago spp.)", pestList: ["Plantains"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply to actively growing plants at the early head stage. Symptoms may be slow to develop." },
          { weed: "Prairie grass (Bromus unioloides) Qld Blue grass (Dichanthium sericeum) Redleg grass (Brothriochloa ambigua) Rhodes grass (Chloris gayana)", pestList: ["Prairie Grass Qld Blue Grass Redleg Grass Rhodes Grass"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply to actively growing plants at the early head stage." },
          { weed: "Rope twitch (Agropyron repens)", pestList: ["Rope Twitch"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply in late Summer-Autumn to actively growing plants with foliage at least 20 cm high. To ensure maximum shoot emergence the area should NOT be cultivated in the period from the preceding Winter until the time of spraying." },
          { weed: "Rushes^ (Juncus spp.)", pestList: ["Rushes^"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply by wiper equipment to actively growing plants. Where there is a large proportion of dead foliage, pre-slashing is recommended. Allow adequate regrowth before treatment. Refer WIPER EQUIPMENT section for application instruction." },
          { weed: "Sedge, tall^ (Carex appressa)", pestList: ["Sedge", "Tall^"], states: ["All"], rate: "2", rateMax: "4", unit: "L/ha", rateText: "2 L or 4 L/ha", notes: "Apply to actively growing plants in flowering to post-flowering period (Oct-Apr). Use the lower rate only if the stand has been slashed prior to treatment. Re-treatment may be necessary. Visible symptoms may not be fully apparent for up to 3 months. Use of CDA equipment is not recommended." },
          { weed: "Silverleaf nightshade (Solanum elaegnifoiium)", pestList: ["Silverleaf Nightshade"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Use ONLY under good soil moisture conditions. Apply to actively growing plants at the late flowering to berry stage. Repeat spraying will be necessary to restrict regrowth and seedling re-establishment." },
          { weed: "Sorrel (Rumex acetosella)", pestList: ["Sorrel"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply to actively growing plants when most have reached the early bud stage. In Conservation Tillage situations, 1.5 L/ha provides seasonal suppression. Refer to Conservation Tillage Uses table." },
          { weed: "Soursob (Oxalis pes-caprae)", pestList: ["Soursob"], states: ["All"], rate: "1.5", unit: "L/ha", rateText: "1.5 L/ha", notes: "For maximum long term reduction apply from late July to early September but before natural plant yellowing (senescence) occurs. Soursob should be actively growing and not under stress of drought or waterlogging. If heavy frosting has occurred allow recovery before spraying. If heavy grazing has occurred allow recovery of foliage to at least 5cm before spraying. In Conservation Tillage (eg. direct drilling) situations, application in May-July immediately prior to sowing will give control of to..." },
          { weed: "St John's wort (Hypericum perforatum)", pestList: ["St John\u2019S Wort"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply to actively growing plants in the flowering to post-flowering, procumbent stem stage (generally Nov-May). Re-treatment or oversowing with improved pasture species may be necessary to restrict seedling re-establishment." },
          { weed: "Thistle, artichoke (Cynara cardunculus)", pestList: ["Thistle", "Artichoke"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply at the rosette-early head stage." },
          { weed: "Thistle, Californian (Cirsium arvense)", pestList: ["Thistle", "Californian"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply to actively growing plants at the flowering stage. To ensure maximum shoot emergence the area should NOT be cultivated prior to spraying. Re-treatment and/or pasture improvement may be necessary to restrict seedling re-establishment." },
          { weed: "Water couch^ (Paspalum distichum)", pestList: ["Water Couch^"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants in late Summer-Autumn (February-March). DO NOT treat after March because of the onset of Winter dormancy. Full results may not be visible until the following Spring. Not more than 1/4 of the weed should be submerged at the time of treatment." },
          { weed: "Water hyacinth^", pestList: ["Water Hyacinth^"], states: ["All"], rate: "6", rateMax: "9", unit: "L/ha", rateText: "6 L-9L/ha", notes: "Apply when actively growing and at or beyond the early bloom stage of growth. Use the higher rate on dense infestations." },
          { weed: "Water lettuce^", pestList: ["Water Lettuce^"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Best results are obtained from mid-Summer through to Winter. Use the higher rate on dense infestations." },
          { weed: "Waterlily, yellow^", pestList: ["Waterlily", "Yellow^"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply when there is a maximum emergence of floating leaves. Allow 2-3 weeks for symptoms to develop and then retreat any unaffected plants. Use low volume sprayer. Refer to Table 6: Aquatic Weed Control." },
          { weed: "Yorkshire fog (Holcus lanatus)", pestList: ["Yorkshire Fog"], states: ["All"], rate: "3", unit: "L/ha", notes: "Apply to actively growing plants at the early head stage." },
          { weed: "Bitou bush/ Boneseed (Chrysanthemoides monilifera)", pestList: ["Bitou Bush/ Boneseed"], states: ["All"], rate: "500", unit: "mL/100L", notes: "Apply to actively growing plants. Spray to wet all foliage. Best results are achieved when treated at peak flowering during Winter. DO NOT apply during periods of drought stress. Use the higher rate on bushes over 1.5m. Further treatment may be necessary to restrict seedling re-establishment. Low Volume Application: (eg. Gas gun and Splatter Gun). Ensure spray contacts all foliage. Use the higher rate (1:19) on bushes over 1.5m high." },
          { weed: "Boxthorn, African (Lycium ferocissimum)", pestList: ["Boxthorn", "African"], states: ["All"], rate: "700", rateMax: "1000", unit: "mL/100L", rateText: "700 mL-1L/100L", notes: "Use the lower rate for young bushes; increase to the higher rate for large, mature bushes. Spray to wet all foliage. DO NOT spray during hot, dry Summer periods. Burning (after complete brownout), pasture improvement and/or further treatment are recommended to control seedlings and/or regrowth. Use of CDA equipment is not recommended." },
          { weed: "Blackberry (Rubus fruticosus)", pestList: ["Blackberry"], states: ["All"], rate: "1", rateMax: "1.3", unit: "L/100L", rateText: "1-1.3 L/100L", notes: "Apply from flowering to leaf fall (generally Jan-May). Plants should not be under stress of high temperature, drought or frost. Spray to wet all foliage. Use the higher rate on old, dense infestations over 2m high. Visible symptoms may not be fully apparent until the next season. Burning (after complete brownout), pasture improvement and/or further treatment are recommended to control seedlings and/or regrowth. Use of CDA equipment is not recommended. In Tasmania, DO NOT treat bushes bearing ..." },
          { weed: "Crofton weed (Eupatorium adenophorum)", pestList: ["Crofton Weed"], states: ["All"], rate: "500", unit: "mL/100L", notes: "Apply to actively growing plants with full foliage. Spray to wet all foliage. Further treatment and/or pasture improvement are recommended to restrict seedling re-establishment." },
          { weed: "Gorse (Furze) (Ulex europaeus)", pestList: ["Gorse (Furze)"], states: ["All"], rate: "1", unit: "L/100L", rateText: "1 L/100L plus Pulse® Penetrant 200mL/100L", notes: "Apply all year round, but only to actively growing plants. Always add Pulse® Penetrant, otherwise reduced results will occur. Spray to wet all foliage. Burning (after complete brownout), pasture improvement and/or further treatment are recommended to control seedlings and/or regrowth." },
          { weed: "Groundsel bush (Baccharis halimifolia)", pestList: ["Groundsel Bush"], states: ["All"], rate: "700", rateMax: "1000", unit: "mL/100L", rateText: "700 mL-1L/100L", notes: "Apply to actively growing plants. DO NOT apply during Winter, nor during periods of Summer drought stress. Use the higher rate on bushes over 2 m tall. Spray to wet all foliage. Further treatment and/or pasture improvement are recommended to control seedlings and/or regrowth. LOW VOLUME APPLICATION (eg. Splatter Gun and Gas Gun): Use 1:9 (10%) mixture of product:water. Apply 2x2 mL dose per 0.5 m bush height. Ensure spray contacts all foliage. Use of CDA equipment is not recommended." },
          { weed: "Hawthorn (Crataegus spp.)", pestList: ["Hawthorn"], states: ["All"], rate: "1", rateMax: "1.3", unit: "L/100L", rateText: "1-1.3 L/100L", notes: "Apply to actively growing plants from flowering to leaf fall. Spray to wet all foliage. Use the higher rate on bushes over 2m tall. Burning (after complete brownout), pasture improvement and/or further treatment are recommended to control seedlings and/or regrowth. LOW VOLUME APPLICATION (eg. Splatter Gun and Gas Gun): Use 1:9 mixture of product:water. Apply 2x5 mL dose per 0.5 m bush height. Ensure spray contacts all foliage." },
          { weed: "Lantana (Lantana camara)", pestList: ["Lantana"], states: ["All"], rate: "1", unit: "L/100L", rateText: "1 L/100L", notes: "Apply to actively growing plants with full foliage. Ensure complete treatment of individual plants. DO NOT spray during periods of Summer drought stress. Burning (after complete brownout), pasture improvement and/or further treatment are recommended to control seedlings and/or regrowth. Addition of Pulse® Penetrant (200 mL/100L) may improve control. LOW VOLUME APPLICATION (eg. Splatter Gun and Gas Gun): Use 1:9 (10%) mixture of product:water. Apply 2x2 mL dose per 0.5 m bush height. Ensure sp..." },
          { weed: "Mistflower (Eupatorium riparium)", pestList: ["Mistflower"], states: ["All"], rate: "500", unit: "mL/100L", notes: "Apply to actively growing plants with full foliage. Spray to wet all foliage. Further treatment and/or pasture improvement are recommended to restrict seedling re-establishment. SPRINKLER SPRAYER: Apply 3 mL of a 1:9 (10%) solution to every square meter of treated area." },
          { weed: "Sifton bush / Chinese scrub (Cassinea arcuata)", pestList: ["Sifton Bush / Chinese Scrub"], states: ["All"], rate: "1", rateMax: "1.3", unit: "L/100L", rateText: "1 L/100L or 1.3 L/100L", notes: "Apply when actively growing. Ensure complete coverage of the bush. Pasture improvement and/or re-treatment is recommended to control seedlings and/or regrowth. HIGH VOLUME: Use the higher rate on bushes over 1m. LOW VOLUME: Apply 40 mL per 0.5 m height. WIPER APPLICATION: Double pass application is required. Application is best made to small (less than 1 m) green bushes." },
          { weed: "Sweet briar (Rosa rubiginosa)", pestList: ["Sweet Briar"], states: ["All"], rate: "1.5", rateMax: "2", unit: "L/100L", rateText: "1.5-2 L/100L", notes: "Apply to actively growing plants from late flowering to leaf fall. Spray to wet all foliage. Use the higher rate on bushes over 1.5 m high. Burning (after complete brownout), pasture improvement and/or further treatment are recommended to control seedlings and/or regrowth. LOW VOLUME APPLICATION: (eg. Splatter Gun and Gas Gun): Use 1:9 (10%) mixture of product:water. Apply 2x5 mL dose per 0.5 m bush height. Ensure spray contacts all foliage." },
          { weed: "Alligator weed", pestList: ["Alligator Weed"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply when actively growing, from Summer through Winter. Floating form only." },
          { weed: "Cumbungi (Typha spp.)", pestList: ["Cumbungi"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants at the early head to full head stage (Summer-Autumn). Re-treatment may be required to restrict seedling re- establishment. Application by wiper equipment is recommended (not Tasmania). Refer WIPER EQUIPMENT section." },
          { weed: "Paragrass (Brachiara mutica)", pestList: ["Paragrass"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants when most have reached the early head stage." },
          { weed: "Phragmites, Common reed (Phragmites australis)", pestList: ["Phragmites", "Common Reed"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing, fully developed plants approaching the early head stage. Visible symptoms of control may be slow to develop and may not be fully apparent until the next season. For application by wiper equipment refer to WIPER EQUIPMENT section." },
          { weed: "Rushes (Juncus spp.)", pestList: ["Rushes"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Apply by wiper equipment to actively growing plants. Where there is a large proportion of dead foliage, pre-slashing is recommended. Allow adequate regrowth before treatment. Refer WIPER EQUIPMENT section for application instruction." },
          { weed: "Sedge, tall (Carex appressa)", pestList: ["Sedge", "Tall"], states: ["All"], rate: "2", rateMax: "4", unit: "L/ha", rateText: "2 L or 4 L/ha", notes: "Apply to actively growing plants in flowering to post-flowering period (Oct-Apr). Use the lower rate only if the stand has been slashed prior to treatment. Re-treatment may be necessary. Visible symptoms may not be fully apparent for up to 3 months. Use of CDA equipment is not recommended." },
          { weed: "Water couch (Paspalum distichum)", pestList: ["Water Couch"], states: ["All"], rate: "9", unit: "L/ha", notes: "Apply to actively growing plants in late Summer-Autumn (February-March). DO NOT treat after March because of the onset of Winter dormancy. Full results may not be visible until the following Spring. Not more than 1/4 of the weed should be submerged at the time of treatment." },
          { weed: "Water hyacinth", pestList: ["Water Hyacinth"], states: ["All"], rate: "6", rateMax: "9", unit: "L/ha", notes: "Apply when actively growing and at or beyond the early bloom stage of growth. Use the higher rate on dense infestations." },
          { weed: "Water lettuce", pestList: ["Water Lettuce"], states: ["All"], rate: "-", unit: "mL/100L", rateText: "-", notes: "Best results are obtained from mid-Summer through to Winter. Use the higher rate on dense infestations." },
          { weed: "Waterlily, yellow", pestList: ["Waterlily", "Yellow"], states: ["All"], rate: "6", unit: "L/ha", notes: "Apply when there is a maximum emergence of floating leaves. Allow 2-3 weeks for symptoms to develop, then retreat any unaffected plants. Use low volume sprayer. Refer to Table 6: Aquatic Weed Control." }
        ]
      }
    ],
    "restraints": [],
    "compatibility": {
        "compatible": [],
        "incompatible": [],
        "notes": []
    },
    "withholding": {
        "harvest": "Not specified",
        "grazing": "Not specified"
    },
    "surfactant": "Not specified",
    "sprayerCleanup": "Not specified"
};
